apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: or49d2fp0-nodejs
  janus-idp.io/tekton: or49d2fp0-nodejs
  backstage.io/kubernetes-id: or49d2fp0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: or49d2fp0-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
